# application.yml 
--- 
spring: 
  application: 
    name: s-service
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 5
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server:
#  port: ${PORT:${SERVER_PORT:0}}
  port: 8080
